# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161104_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alerts_checked_at',
        ),
    ]
