# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161205_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, null=True, max_length=100, unique=True),
        ),
    ]
