# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='This name will be displayed publicly if you post any notices', max_length=100, null=True, unique=True),
        ),
    ]
