# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_last_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
