# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 20:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_auto_20161030_0714'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='notice',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
            preserve_default=False,
        ),
    ]
