# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_auto_20161121_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
