# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 19:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0013_auto_20161122_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='tags',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='e.g. type:planning application, organisation:House of Wine, items-required:beans,tampons,toothpaste', null=True),
        ),
    ]
