# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0014_auto_20161129_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(help_text="e.g. 'Application for alcohol licence - House of Wine' or 'Westlow Food Bank - items required'", max_length=80),
        ),
    ]
