# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-29 14:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_notice_notice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_type',
        ),
        migrations.AddField(
            model_name='notice',
            name='location',
            field=django.contrib.gis.db.models.fields.GeometryField(default='', srid=4326),
            preserve_default=False,
        ),
    ]
