# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-30 07:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20161029_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 30, 7, 14, 41, 859929)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 30, 7, 14, 46, 434982)),
            preserve_default=False,
        ),
    ]
