# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 15:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_notice_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
