# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 09:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_auto_20161121_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
