# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import main.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161104_1205'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', main.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
